In [27]:
import numpy as np
from sklearn.datasets import load_wine

In [28]:
X,y = load_wine(return_X_y=True)

In [29]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [30]:
X.shape

(178, 13)

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [32]:
y.shape

(178,)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [35]:
print(X_train.shape)
print(X_test.shape)

(142, 13)
(36, 13)


In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
reg = LinearRegression()

In [38]:
reg.fit(X_train,y_train)

LinearRegression()

In [39]:
y_pred = reg.predict(X_test)

In [40]:
from sklearn.metrics import r2_score

In [41]:
r2_score(y_test,y_pred)

0.8953485179220059

In [42]:
reg.coef_

array([-0.12733656,  0.03834954, -0.19024208,  0.05105101, -0.00065852,
        0.16775645, -0.4056201 , -0.27120573,  0.01230411,  0.09376003,
       -0.11255068, -0.17858751, -0.00067898])

In [43]:
reg.intercept_

np.float64(3.1579343856458295)

In [44]:
class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred



In [45]:
lr = MeraLR()

In [46]:
lr.fit(X_train,y_train)

In [47]:
X_train.shape

(142, 13)

In [48]:
np.insert(X_train,0,1,axis=1).shape

(142, 14)

In [49]:
y_pred = lr.predict(X_test)

In [50]:
r2_score(y_test,y_pred)

0.895348517922013

In [51]:
lr.coef_

array([-0.12733656,  0.03834954, -0.19024208,  0.05105101, -0.00065852,
        0.16775645, -0.4056201 , -0.27120573,  0.01230411,  0.09376003,
       -0.11255068, -0.17858751, -0.00067898])

In [52]:
lr.intercept_

np.float64(3.1579343856453717)